import type { TransactionCategory } from "./types"

export const CATEGORIES: TransactionCategory[] = [
  "Groceries",
  "Restaurants & Dining",
  "Coffee & Cafes",
  "Fast Food",
  "Alcohol & Bars",
  "Rent & Mortgage",
  "Utilities",
  "Internet & Phone",
  "Insurance",
  "Gas & Fuel",
  "Public Transit",
  "Ride Share",
  "Travel & Flights",
  "Hotels & Accommodation",
  "Streaming & Media",
  "Software & Apps",
  "Gym & Fitness",
  "Clothing & Apparel",
  "Electronics",
  "Home & Garden",
  "Personal Care & Beauty",
  "Pharmacy & Medicine",
  "Doctor & Dental",
  "Education",
  "Pet Care",
  "Charity & Donations",
  "ATM & Banking",
  "Transfers",
  "Investments",
  "Other",
]

export const CATEGORY_COLORS: Record<TransactionCategory, string> = {
  "Groceries": "#10b981",
  "Restaurants & Dining": "#34d399",
  "Coffee & Cafes": "#6ee7b7",
  "Fast Food": "#a7f3d0",
  "Alcohol & Bars": "#f472b6",
  "Rent & Mortgage": "#3b82f6",
  "Utilities": "#60a5fa",
  "Internet & Phone": "#93c5fd",
  "Insurance": "#bfdbfe",
  "Gas & Fuel": "#f97316",
  "Public Transit": "#fb923c",
  "Ride Share": "#fdba74",
  "Travel & Flights": "#fcd34d",
  "Hotels & Accommodation": "#fde68a",
  "Streaming & Media": "#a855f7",
  "Software & Apps": "#c084fc",
  "Gym & Fitness": "#d8b4fe",
  "Clothing & Apparel": "#f59e0b",
  "Electronics": "#fbbf24",
  "Home & Garden": "#84cc16",
  "Personal Care & Beauty": "#ec4899",
  "Pharmacy & Medicine": "#06b6d4",
  "Doctor & Dental": "#22d3ee",
  "Education": "#67e8f9",
  "Pet Care": "#4ade80",
  "Charity & Donations": "#e2e8f0",
  "ATM & Banking": "#a3e635",
  "Transfers": "#cbd5e1",
  "Investments": "#38bdf8",
  "Other": "#64748b",
}

export const CATEGORY_BG: Record<TransactionCategory, string> = {
  "Groceries": "bg-emerald-500/20 text-emerald-400",
  "Restaurants & Dining": "bg-emerald-400/20 text-emerald-300",
  "Coffee & Cafes": "bg-emerald-300/20 text-emerald-300",
  "Fast Food": "bg-emerald-200/20 text-emerald-300",
  "Alcohol & Bars": "bg-pink-400/20 text-pink-400",
  "Rent & Mortgage": "bg-blue-500/20 text-blue-400",
  "Utilities": "bg-blue-400/20 text-blue-400",
  "Internet & Phone": "bg-blue-300/20 text-blue-300",
  "Insurance": "bg-blue-200/20 text-blue-300",
  "Gas & Fuel": "bg-orange-500/20 text-orange-400",
  "Public Transit": "bg-orange-400/20 text-orange-400",
  "Ride Share": "bg-orange-300/20 text-orange-300",
  "Travel & Flights": "bg-yellow-400/20 text-yellow-400",
  "Hotels & Accommodation": "bg-yellow-300/20 text-yellow-300",
  "Streaming & Media": "bg-purple-500/20 text-purple-400",
  "Software & Apps": "bg-purple-400/20 text-purple-400",
  "Gym & Fitness": "bg-purple-300/20 text-purple-300",
  "Clothing & Apparel": "bg-amber-500/20 text-amber-400",
  "Electronics": "bg-amber-400/20 text-amber-400",
  "Home & Garden": "bg-lime-500/20 text-lime-400",
  "Personal Care & Beauty": "bg-pink-500/20 text-pink-400",
  "Pharmacy & Medicine": "bg-cyan-500/20 text-cyan-400",
  "Doctor & Dental": "bg-cyan-400/20 text-cyan-400",
  "Education": "bg-cyan-300/20 text-cyan-300",
  "Pet Care": "bg-green-400/20 text-green-400",
  "Charity & Donations": "bg-slate-300/20 text-slate-300",
  "ATM & Banking": "bg-lime-400/20 text-lime-400",
  "Transfers": "bg-slate-400/20 text-slate-300",
  "Investments": "bg-sky-400/20 text-sky-400",
  "Other": "bg-slate-500/20 text-slate-400",
}

export const CATEGORY_EMOJIS: Record<TransactionCategory, string> = {
  "Groceries": "🛒",
  "Restaurants & Dining": "🍽️",
  "Coffee & Cafes": "☕",
  "Fast Food": "🍔",
  "Alcohol & Bars": "🍺",
  "Rent & Mortgage": "🏠",
  "Utilities": "💡",
  "Internet & Phone": "📡",
  "Insurance": "🛡️",
  "Gas & Fuel": "⛽",
  "Public Transit": "🚌",
  "Ride Share": "🚕",
  "Travel & Flights": "✈️",
  "Hotels & Accommodation": "🏨",
  "Streaming & Media": "🎬",
  "Software & Apps": "💻",
  "Gym & Fitness": "🏋️",
  "Clothing & Apparel": "👗",
  "Electronics": "📱",
  "Home & Garden": "🪴",
  "Personal Care & Beauty": "💄",
  "Pharmacy & Medicine": "💊",
  "Doctor & Dental": "🏥",
  "Education": "📚",
  "Pet Care": "🐾",
  "Charity & Donations": "❤️",
  "ATM & Banking": "🏧",
  "Transfers": "💸",
  "Investments": "📈",
  "Other": "📦",
}
